# frozen_string_literal: true
# rake app:init
namespace :app do
  task load: :environment do
    puts '----> Migrations'

    Rake::Task['db:migrate'].invoke

    puts '----> Seeding users'

    Rake::Task['seed:users'].invoke

    puts '----> Creating Europeana Project'

    Core::Project.create(account_id: 1, name: 'Europeana')

    puts '----> Loading Ref::Chart'
    Ref::Chart.destroy_all
    # headers name,slug,description,img_small,img_data_mapping,api,sort_order,genre,combination_code,source,file_path,map
    CSV.read(Dir[File.join(Rails.root, 'db', 'seeds', 'ref','chart.csv')].first).each_with_index do |line, index|
      next if index == 0 # skipping header
      name             = line[0]
      slug             = line[1]
      description      = line[2]
      img_small        = line[3]
      img_data_mapping = line[4]
      api              = line[5]
      sort_order       = line[6]
      genre            = line[7]
      cc_code          = line[8] || SecureRandom.hex(3) # it produces a random hex code when no combination_code is present in the csv
      source           = line[9]
      file_path        = line[10]
      map              = line[11]

      Ref::Chart.create!(name: name,
                         slug: slug,
                         description: description,
                         img_small: img_small,
                         img_data_mapping: img_data_mapping,
                         api: api,
                         sort_order: sort_order,
                         genre: genre,
                         combination_code: cc_code,
                         source: source,
                         file_path: file_path,
                         map: map)
    end

    puts '----> Loading Core::Theme'
    Core::Theme.admin.destroy_all
    # header name,config,account_id,sort_order,image_url
    CSV.read(Dir[File.join(Rails.root, 'db', 'seeds', 'core','themes.csv')].first).each_with_index do |line, index|
      next if index == 0 # skipping header
      name           = line[0]
      config         = line[1]
      account_id     = line[2]
      sort_order     = line[3]
      image_url      = line[4]
      Core::Theme.create(name: name, config: config, account_id: account_id, sort_order: sort_order, image_url: image_url)
    end

    puts '----> Loading Ref::CountryCode'
    CSV.read(Dir[File.join(Rails.root, 'db', 'seeds', 'ref','country_code.csv')].first).each do |line|
      code = line[0]
      country = line[1]
      Ref::CountryCode.find_or_create(code, country)
    end
  end

  task create_default_template: :environment do
    puts '----> Creating Default Template for data providers'
    name = 'Default Europeana Template'
    genre = 'europeana'
    required_variables = { 'required_variables' => %w(main_chart topcountries total_items open_for_reuse) }
    html_content = ' '
    Core::Template.create_or_update(name, html_content, genre, required_variables)
  end

  task create_or_update_europeana_aggregation_report: :environment do
    puts '----> Building Europeana'
    core_project_id = Core::Project.where(name: 'Europeana').first.id
    name = 'Europeana'
    genre = 'europeana'
    europeana_impl_aggregation = Impl::Aggregation.create_or_find_aggregation(name, genre, core_project_id)
    #Impl::DataProviders::MediaTypesBuilder.perform_async(Impl::Aggregation.europeana.id)
    #Aggregations::Europeana::PageviewsBuilder.perform_async
  end

  task seed_europeana_production_reports: :environment do
    puts '----> Seeding Production Report'
    CSV.read(Dir[File.join(Rails.root, 'db', 'seeds', 'impl','reports_backup.csv')].first).each_with_index do |line, index|
      next if index == 0
      name = line[0]
      slug = name.downcase.gsub(" ", "-")
      html_content = line[1]
      Impl::Report.create(name: name, html_content: html_content, slug: slug, variable_object: {}, is_autogenerated: false)
    end

  end

  task init: :environment do
    Rake::Task['app:load'].invoke
    Rake::Task['app:create_default_template'].invoke
    Rake::Task['app:create_or_update_europeana_aggregation_report'].invoke
    Rake::Task['app:seed_europeana_production_reports'].invoke
  end
end