notifications:
  email: false
sudo: false
branches:
  only:
    - master
    - develop
language: ruby
rvm:
  - 2.3.1
addons:
  postgresql: "9.4"
before_install:
  - "cp deploy/travis/config/database.yml config/database.yml"
  - "cp deploy/travis/config/redis.yml config/redis.yml"
before_script:
  - psql --version
  - RAILS_ENV=test bundle exec rake db:create
  - RAILS_ENV=test bundle exec rake db:migrate
script: bundle exec rspec
env:
  - RAILS_ENV=test
services:
  - redis-server
  - postgresql
