pg: &pg
  adapter: postgresql
  encoding: unicode
  pool: 20

development:
  <<: *pg
  port: 5432
  database: datastory2
  host: localhost
  username: developer
  password: developer

staging:
  <<: *pg
  port: 5432
  host: localhost
  username: rumidbuser
  password: 28bcda0b760a