# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c8b4c8a9e2c29f4a4851cff37c538029f90326a3c4359c914a7629469f969ca0337a60d350498b55e44a1fae871374e4eb32f6d677c6475f4c86976049ec70c7

test:
  secret_key_base: f8fcb4ffe6a2cb4cbbabe9d0c9a8f7a022ab1b03bd89ba2e3e2b5d92a1b651c9d2a989b79731f9ea01d44d6d92249a839697116ab805501db484f8598ed9aba6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
