development:
  host: <%= ENV['REDIS_HOST'] || 'localhost' %>
  port: <%= ENV['REDIS_PORT'] || 6379 %>
  name: <%= ENV['REDIS_NAME'] || 'redis' %>
  db: <%= ENV['REDIS_DB'] || 0 %>
  namespace: <%= ENV['REDIS_NAMESPACE'] || 'cache' %>
