# frozen_string_literal: true
class AddColsToCoreViz < ActiveRecord::Migration
  def change
    add_column :core_vizs, :is_autogenerated, :boolean, default: false
    Core::Viz.all.each do |viz|
      viz.update_column(:is_autogenerated, true)
    end
  end
end
