class AddColsToReports < ActiveRecord::Migration
  def change
    add_column :impl_reports, :impl_aggregation_genre, :string
    Impl::Report.where(is_autogenerated: true).includes(:impl_aggregation).each do |r|
      r.update_column(:impl_aggregation_genre, r.impl_aggregation.genre)
    end
  end
end
